In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Welcome\Desktop\customer2.csv", 
                 encoding="latin1",
                 on_bad_lines="skip"
)
df.head()

,ï»¿id,age,gender,income,education,region,loyalty_status,purchase_frequency,purchase_amount,product_category,promotion_usage,satisfaction_score
0,1,27,Male,40682,Bachelor,East,Gold,frequent,18249,Books,0,6
1,2,29,Male,15317,Masters,West,Regular,rare,4557,Clothing,1,6
2,3,37,Male,38849,Bachelor,West,Silver,rare,11822,Clothing,0,6
3,4,30,Male,11568,HighSchool,South,Regular,frequent,4098,Food,0,7
4,5,31,Female,46952,College,North,Regular,occasional,19685,Clothing,1,5

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ï»¿id               100000 non-null  int64
 1   age                 100000 non-null  int64
 2   gender              100000 non-null  object
 3   income              100000 non-null  int64
 4   education           100000 non-null  object
 5   region              100000 non-null  object
 6   loyalty_status      100000 non-null  object
 7   purchase_frequency  100000 non-null  object
 8   purchase_amount     100000 non-null  int64
 9   product_category    100000 non-null  object
 10  promotion_usage     100000 non-null  int64
 11  satisfaction_score  100000 non-null  int64
dtypes: int64(6), object(6)
memory usage: 9.2+ MB

In [4]:
df.describe(include="all")

,ï»¿id,age,gender,income,education,region,loyalty_status,purchase_frequency,purchase_amount,product_category,promotion_usage,satisfaction_score
count,100000.000000,100000.000000,100000,100000.000000,100000,100000,100000,100000,100000.000000,100000,100000.000000,100000.000000
unique,NaN,NaN,2,NaN,4,4,3,3,NaN,7,NaN,NaN
top,NaN,NaN,Female,NaN,College,East,Regular,rare,NaN,Electronics,NaN,NaN
freq,NaN,NaN,50074,NaN,39874,30074,60138,50019,NaN,30027,NaN,NaN
mean,50000.500000,30.003260,NaN,27516.269880,NaN,NaN,NaN,NaN,9634.790840,NaN,0.300800,5.009650
std,28867.657797,4.480535,NaN,12996.782587,NaN,NaN,NaN,NaN,4799.339449,NaN,0.458608,1.038714
min,1.000000,12.000000,NaN,5000.000000,NaN,NaN,NaN,NaN,1118.000000,NaN,0.000000,0.000000
25%,25000.750000,27.000000,NaN,16271.750000,NaN,NaN,NaN,NaN,5583.000000,NaN,0.000000,4.000000
50%,50000.500000,30.000000,NaN,27584.500000,NaN,NaN,NaN,NaN,9452.000000,NaN,0.000000,5.000000
75%,75000.250000,33.000000,NaN,38747.250000,NaN,NaN,NaN,NaN,13350.000000,NaN,1.000000,6.000000
max,100000.000000,49.000000,NaN,50000.000000,NaN,NaN,NaN,NaN,26204.000000,NaN,1.000000,10.000000

In [5]:
df.isnull().sum()

ï»¿id                 0
age                   0
gender                0
income                0
education             0
region                0
loyalty_status        0
purchase_frequency    0
purchase_amount       0
product_category      0
promotion_usage       0
satisfaction_score    0
dtype: int64

In [6]:
labels = ['Adults','Middle_aged']
df['age_group'] = pd.qcut(df['age'], q=2, labels=labels)
df[['age', 'age_group']].head(10)

   age    age_group
0   27       Adults
1   29       Adults
2   37  Middle_aged
3   30       Adults
4   31  Middle_aged
5   38  Middle_aged
6   32  Middle_aged
7   24       Adults
8   27       Adults
9   28       Adults

In [10]:
!pip install sqlalchemy mysql-connector-python

Requirement already satisfied: sqlalchemy in c:\users\welcome\anaconda3\lib\site-packages (2.0.43)
Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: greenlet>=1 in c:\users\welcome\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\welcome\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---- ----------------------------------- 1.8/17.7 MB 8.5 MB/s eta 0:00:02
   ------ --------------------------------- 2.9/17.7 MB 9.8 MB/s eta 0:00:02
   ------------- -------------------------- 5.8/17.7 MB 8.6 MB/s eta 0:00:02
   --------------------- ------------------ 9.7/17.7 MB 10.7 MB/s eta 0:00:01
   -------------------------------- ------- 14.2/17.7 MB 12.6 MB/s eta 0:00:01
   ----------------------------------- ---- 15.7/17.7 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------  17.3/17.7 MB 11.1 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 10.1 MB/s  0:00:01
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0

In [18]:
from sqlalchemy import create_engine
import pandas as pd

# Step 1: Connect to MySQL - database ab exist karta hai
username = "root"           
password = "root123" # <- APNA PASSWORD DAALO
host = "localhost"          
port = "3306"               
database = "customer_db"    

engine = create_engine(f"mysql+mysqlconnector://{username}:{password}@{host}:{port}/{database}")

# Step 2: CSV load karo aur upload kar do
df = pd.read_csv(r'C:\Users\Welcome\Desktop\customer2.csv', encoding='utf-8-sig') # <- YAHAN PURA KAR
df.columns = ['id', 'age', 'gender', 'income', 'education', 'region', 
              'loyalty_status', 'purchase_frequency', 'purchase_amount', 
              'product_category', 'promotion', 'satisfaction_score']

table_name = "customers"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customers' in database 'customer_db'.